apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvendas-pv
  labels:
    type: local
    app: {{ .Release.Name }}-db
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.size }}Gi
  accessModes:
    - {{ .Values.storage.acessModes }}
  hostPath:
    path: "/data/dbvendas-pv"
