kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dbvendas-pv-claim
  labels:
    app: dbvendas
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi