apiVersion: v1
kind: PersistentVolume
metadata:
  name: dbvendas-pv
  labels:
    type: local
    app: dbvendas
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/dbvendas-pv"
