image: maven:3.6.3-openjdk-11-slim

stages:
  - test
  - build
  - sonar
  - docker
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s ./settings.xml"

maven-test:
  stage: test
  extends: .retry-on-system-failures
  script:
    - mvn $MAVEN_CLI_OPTS clean verify
    - echo -n "Jacoco-Test-Coverage:" ; cat $CI_PROJECT_DIR/target/site/jacoco/index.html | grep -o 'Total[^%]*%' | grep -o -E '[0-9]+%$'
  coverage: /Jacoco-Test-Coverage.*?([0-9]{1,3})%/
  cache:
    key: m2repository
    paths:
      - .m2/repository
      - target/

maven-build:
  stage: build
  extends: .retry-on-system-failures
  script:
    - mvn $MAVEN_CLI_OPTS -DskipTests clean package
  cache:
    key: m2repository
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1h

sonar:
  stage: sonar
  extends: .retry-on-system-failures
  before_script:
    - export PROJECT_KEY_SONAR=$APP_GROUP-$APP_SUBGROUP-$APP_NAME-${CI_COMMIT_REF_NAME}
    - export PROJECT_NAME_SONAR=$(echo "$APP_GROUP $APP_SUBGROUP $APP_NAME [$CI_COMMIT_REF_NAME]")
  script:
    - mvn test -s ./settings.xml sonar:sonar -DskipTests=true
  cache:
    key: m2repository
    paths:
      - .m2/repository
      - target/


include:
  - project: devops/ship
    file: /templates/exceptions/.retry-on-system-failures.yml
  - project: devops/ship
    file: /templates/docker/.job-docker-gitlab-registry-alpha.yml
  - project: devops/ship
    file: /templates/deploy/.job-deploy-gke-with-helm.yml